/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddelivery;

import com.sun.glass.events.KeyEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Imbamizi
 */
public class Customer extends javax.swing.JFrame {

    Message ms = new Message();

    public void customerView() {
        javax.swing.table.DefaultTableModel dt = new javax.swing.table.DefaultTableModel();
        Dtable.setModel(dt);
        Dtable.setDefaultEditor(Object.class, null);
        dt.addColumn("Food/Drinks Code");
        dt.addColumn("Food/Drinks Name");
        dt.addColumn("Food/Drinks Price");
        String filepath = "DetailsFile\\foodDetails.txt";
        File f = new File(filepath);

        try {
            BufferedReader br;
            br = new BufferedReader(new FileReader(f));

            Object[] tableLines = br.lines().toArray();

            for (int i = 0; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                dt.addRow(dataRow);
            }
            br.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public int Actualrows(javax.swing.JTable om) {
        int row = 0;
        int i = 0;
        for (i = 0; i < om.getRowCount(); ++i) {
            try {
                if (!(om.getValueAt(i, 0).equals("")) && !(om.getValueAt(i, 1).equals(""))
                        && !(om.getValueAt(i, 2).equals(""))) {
                    row++;
                }
            } catch (NullPointerException e) {
                continue;
            }
        }
        return row;
    }

    public class LengthRestrictedDocument extends PlainDocument {

        private int limit;

        public LengthRestrictedDocument(int limit) {
            this.limit = limit;
        }

        public void insertString(int offs, String str, AttributeSet a)
                throws BadLocationException {
            if (str == null) {
                return;
            }

            if ((getLength() + str.length()) <= limit) {
                super.insertString(offs, str, a);
            }
        }
    }

    public static boolean inNumVal(String in) {
        return in.charAt(0) == '0' && in.charAt(1) == '1' || in.charAt(1) == '6' || in.charAt(1) == '3' && in.length() == 11 || in.length() == 10;
    }

    public Customer() {
        initComponents();
        showDate();
        showTime();
    }

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd|MM|yyyy");
        Datelab.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                Timelab.setText(s.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BackButton = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Dtable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        smsg = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField2.setDocument(new LengthRestrictedDocument(11));
        jLabel11 = new javax.swing.JLabel();
        Timelab = new javax.swing.JLabel();
        Datelab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Male_User_96px.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("CUSTOMER INTERFACE");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("\"Make a great choice\"");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        BackButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        BackButton.setForeground(new java.awt.Color(204, 204, 204));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Back_To_52px_1.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        jPanel2.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        Dtable.setBackground(new java.awt.Color(0, 0, 0));
        Dtable.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 16)); // NOI18N
        Dtable.setForeground(new java.awt.Color(153, 153, 153));
        Dtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food/Drinks Code", "Food/Drinks Name", "Food/Drinks Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Dtable.setColumnSelectionAllowed(true);
        Dtable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(Dtable);
        Dtable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (Dtable.getColumnModel().getColumnCount() > 0) {
            Dtable.getColumnModel().getColumn(0).setResizable(false);
            Dtable.getColumnModel().getColumn(1).setResizable(false);
            Dtable.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 370, 180));

        OrderTable.setBackground(new java.awt.Color(0, 0, 0));
        OrderTable.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 16)); // NOI18N
        OrderTable.setForeground(new java.awt.Color(153, 153, 153));
        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food/Drinks Code", "Food/Drinks Name", "Food/Drinks Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        OrderTable.setColumnSelectionAllowed(true);
        OrderTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(OrderTable);
        OrderTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 360, 180));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Select_25px.png"))); // NOI18N
        jLabel2.setText("Select");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, 40));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Shopping_Cart_52px.png"))); // NOI18N
        jLabel3.setText("ORDER");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, -1, 70));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 10, 280));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 25)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Empty_Set_25px.png"))); // NOI18N
        jLabel7.setText("Clear ");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, -1, 40));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Remove_25px.png"))); // NOI18N
        jLabel8.setText("Delete selected");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 150, 40));

        smsg.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 16)); // NOI18N
        smsg.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(smsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 270, 30));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Enter name:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Enter phone number:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, 30));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, 200, 30));

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 140, 30));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 290, 20));

        Timelab.setBackground(new java.awt.Color(204, 204, 204));
        Timelab.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        Timelab.setForeground(new java.awt.Color(204, 204, 204));
        Timelab.setText("hh-mm-ss");
        jPanel2.add(Timelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 60, 130, 20));

        Datelab.setBackground(new java.awt.Color(204, 204, 204));
        Datelab.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        Datelab.setForeground(new java.awt.Color(204, 204, 204));
        Datelab.setText("yyyy-mm-dd");
        jPanel2.add(Datelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 130, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        javax.swing.table.TableModel om = Dtable.getModel();
        int[] indexs = Dtable.getSelectedRows();
        Object[] row = new Object[3];
        javax.swing.table.DefaultTableModel om1 = (javax.swing.table.DefaultTableModel) OrderTable.getModel();
        for (int i = 0; i < indexs.length; i++) {
            row[0] = om.getValueAt(indexs[i], 0);
            row[1] = om.getValueAt(indexs[i], 1);
            row[2] = om.getValueAt(indexs[i], 2);
            om1.addRow(row);
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) OrderTable.getModel();
        dt.setRowCount(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) OrderTable.getModel();
        int[] rows = OrderTable.getSelectedRows();
        for (int i = 0; i < rows.length; i++) {
            model.removeRow(rows[i] - i);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd/MM/yyyy");
        double total = 0.0;
        String tp;
        Message ms = new Message();
        String nm = jTextField1.getText();
        ms.setNama(nm);

        if (!jTextField1.getText().equals("") && !jTextField2.getText().equals("") && inNumVal(jTextField2.getText()) && OrderTable.getRowCount() > 0) {

            try {
                File fpath = new File("DetailsFile\\CustomerOrder");
                File f = new File(fpath, jTextField1.getText() + ".txt");
                File nf = new File("DetailsFile\\Management\\totalorderdetails.txt");
                if (f.exists()) {

                    int coun = 1;
                    while (f.exists()) {
                        f = new File(fpath, jTextField1.getText() + "NewOrder" + coun + ".txt");
                        coun++;
                    }
                }
                FileWriter fw = new FileWriter(f, true);
                FileWriter nfw = new FileWriter(nf, true);
                BufferedWriter bw = new BufferedWriter(fw);
                BufferedWriter nbw = new BufferedWriter(nfw);
                bw.write(jTextField1.getText() + "/" + jTextField2.getText() + "/");
                bw.write(Datelab.getText() + "/" + Timelab.getText() + "/");
                for (int i = 0; i < OrderTable.getRowCount(); i++) {
                    total = total + Double.parseDouble((String) OrderTable.getModel().getValueAt(i, 2));
                }
                tp = String.valueOf(total);
                bw.write(tp + "/");
                nbw.write(s.format(d) + "/" + jTextField1.getText() + "/" + tp);
                nbw.newLine();
                nbw.close();
                nfw.close();
                bw.newLine();
                for (int i = 0; i < OrderTable.getRowCount(); i++) {
                    for (int j = 0; j < OrderTable.getColumnCount(); j++) {
                        bw.write((String) OrderTable.getModel().getValueAt(i, j) + "/");
                    }

                    bw.newLine();
                }
                bw.close();
                fw.close();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            ms.showPrice();
            ms.setVisible(true);
        } else {
            jLabel11.setText("Please complete required fields");
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        smsg.setText("");
        jLabel11.setText("");
    }//GEN-LAST:event_jLabel3MouseExited

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        jLabel11.setText("");
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char vchar = evt.getKeyChar();
        if (!(Character.isDigit(vchar))
                || (vchar == KeyEvent.VK_BACKSPACE)
                || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackButton;
    private javax.swing.JLabel Datelab;
    private javax.swing.JTable Dtable;
    private javax.swing.JTable OrderTable;
    private javax.swing.JLabel Timelab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel smsg;
    // End of variables declaration//GEN-END:variables
}
