/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddelivery;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.Object;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
public class Input extends javax.swing.JFrame {
private int r,c;
public String foodname[];
public String foodcode[];
public String foodprice[];


    
    public Input() {
        initComponents();
    }
    
    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd|MM|yyyy");
        Datelab.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                Timelab.setText(s.format(d));
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Header = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BackButton = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabe1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Dtable = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        ermsg = new javax.swing.JLabel();
        smsg = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Timelab = new javax.swing.JLabel();
        Datelab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 40)); // NOI18N
        Header.setForeground(new java.awt.Color(204, 204, 204));
        Header.setText("ITEMS INPUT");
        jPanel2.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Input your items detail");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        BackButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        BackButton.setForeground(new java.awt.Color(204, 204, 204));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Back_To_52px_1.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        jPanel2.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 10, 100));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Add_List_96px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 110, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Save_64px.png"))); // NOI18N
        jLabel2.setText("Save");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, -1, -1));

        LogoutButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(204, 204, 204));
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Sign_Out_25px.png"))); // NOI18N
        LogoutButton.setText("Log out");
        LogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });
        jPanel2.add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Number of items :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 30));

        jLabe1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 15)); // NOI18N
        jLabe1.setForeground(new java.awt.Color(153, 153, 153));
        jLabe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Checked_25px_1.png"))); // NOI18N
        jLabe1.setText("Confirm");
        jLabe1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabe1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, 30));

        Dtable.setBackground(new java.awt.Color(0, 0, 0));
        Dtable.setBorder(new javax.swing.border.MatteBorder(null));
        Dtable.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 14)); // NOI18N
        Dtable.setForeground(new java.awt.Color(153, 153, 153));
        Dtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food/Drinks Category", "Food/Drinks Name", "Food/Drinks Price"
            }
        ));
        Dtable.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(Dtable);
        Dtable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 640, 100));

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("0");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 40, 30));

        ermsg.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 16)); // NOI18N
        ermsg.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(ermsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 270, 20));

        smsg.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 16)); // NOI18N
        smsg.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(smsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 70, 20));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Empty_Set_25px.png"))); // NOI18N
        jLabel6.setText("Clear ");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, -1, -1));

        Timelab.setBackground(new java.awt.Color(204, 204, 204));
        Timelab.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        Timelab.setForeground(new java.awt.Color(204, 204, 204));
        Timelab.setText("hh:MM:ss a");
        jPanel2.add(Timelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 100, 20));

        Datelab.setBackground(new java.awt.Color(204, 204, 204));
        Datelab.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        Datelab.setForeground(new java.awt.Color(204, 204, 204));
        Datelab.setText("dd|MM|yyyy");
        jPanel2.add(Datelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 100, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        User us = new User();
        us.setVisible(true);
        dispose();
    }//GEN-LAST:event_BackButtonMouseClicked

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         try{
         File f = new File("DetailsFile\\foodDetails.txt");
         if(!f.exists()){
             f.createNewFile();
         }
         FileWriter fw = new FileWriter(f,true);
         BufferedWriter bw = new BufferedWriter(fw);
         
         for(int i=0; i<Dtable.getRowCount(); i++){
             for(int j=0; j<Dtable.getColumnCount(); j++){                
                 bw.write(Dtable.getModel().getValueAt(i, j)+ "/");
             }
             bw.newLine();
         }
         bw.close();
         fw.close();
         smsg.setText("Saved");
     }
     catch(Exception ex){
         ex.printStackTrace();
     }
     
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabe1MouseClicked
       javax.swing.table.DefaultTableModel dt = new javax.swing.table.DefaultTableModel();
       try{
            int ps = Integer.parseInt(jTextField1.getText());
            Dtable.setModel(dt);
            dt.addColumn("Food/Drinks Category");
            dt.addColumn("Food/Drinks Name");
            dt.addColumn("Food/Drinks Price");
            
            for(int x=0; x<ps; x++){
                dt.addRow(new Object[]{x+1});
            }
            }catch(Exception e){
                e.printStackTrace();
            }   
        
     
    }//GEN-LAST:event_jLabe1MouseClicked

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        smsg.setText("");
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        javax.swing.table.DefaultTableModel dt = (javax.swing.table.DefaultTableModel) Dtable.getModel();
        dt.setRowCount(0);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackButton;
    private javax.swing.JLabel Datelab;
    private javax.swing.JTable Dtable;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel LogoutButton;
    private javax.swing.JLabel Timelab;
    private javax.swing.JLabel ermsg;
    private javax.swing.JLabel jLabe1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel smsg;
    // End of variables declaration//GEN-END:variables
}
