/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fooddelivery;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Comparator;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;

/**
 *
 * @author Imbamizi
 */
public class OrderView extends javax.swing.JFrame {

    public String totalprice;

    void showDate() {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd|MM|yyyy");
        Datelab.setText(s.format(d));
    }

    void showTime() {
        new Timer(0, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
                Timelab.setText(s.format(d));
            }
        }).start();
    }

    private String vieworder;

    public OrderView() {
        initComponents();
        showDate();
        showTime();
    }

    public void getFilesName() {
        File file = new File("DetailsFile/CustomerOrder");
        File[] files = file.listFiles();
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) CustomerOrder.getModel();
        model.setColumnIdentifiers(new String[]{"Customer Orders"});

        Arrays.sort(files, new Comparator<File>() {
            public int compare(File f1, File f2) {
                return Long.valueOf(f1.lastModified()).compareTo(f2.lastModified());
            }
        });
        Object[] row = new Object[1];
        model.setRowCount(0);

        for (int i = 0; i < files.length; i++) {
            row[0] = files[i].getName().replaceFirst("[.][^.]+$", "");
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BackButton = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JLabel();
        smsg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerOrder = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        ViewTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vDetails = new javax.swing.JLabel();
        complete = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        nombor = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ttprice = new javax.swing.JLabel();
        Datelab = new javax.swing.JLabel();
        Timelab = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("VIEW ORDERS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("View your customer's order");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        BackButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 30)); // NOI18N
        BackButton.setForeground(new java.awt.Color(204, 204, 204));
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Back_To_52px_1.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        jPanel2.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 10, 100));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Edit_Property_96px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 110, -1));

        LogoutButton.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(204, 204, 204));
        LogoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Sign_Out_25px.png"))); // NOI18N
        LogoutButton.setText("Log out");
        LogoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
        });
        jPanel2.add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        smsg.setFont(new java.awt.Font("Tw Cen MT Condensed", 2, 16)); // NOI18N
        smsg.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.add(smsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 70, 20));

        CustomerOrder.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 16)); // NOI18N
        CustomerOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Orders"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CustomerOrder.setColumnSelectionAllowed(true);
        CustomerOrder.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(CustomerOrder);
        CustomerOrder.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 160, 250));

        ViewTable.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 16)); // NOI18N
        ViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food/Drinks Code", "Food/Drinks Name", "Food/Drinks Price"
            }
        ));
        ViewTable.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(ViewTable);
        ViewTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 500, 280));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("NAME :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("PHONE NUMBER :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, 30));

        vDetails.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        vDetails.setForeground(new java.awt.Color(204, 204, 204));
        vDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_View_25px.png"))); // NOI18N
        vDetails.setText("View Details");
        vDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        vDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vDetailsMouseClicked(evt);
            }
        });
        jPanel2.add(vDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        complete.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        complete.setForeground(new java.awt.Color(204, 204, 204));
        complete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fooddelivery/icons8_Checked_Checkbox_25px_1.png"))); // NOI18N
        complete.setText("Order Complete");
        complete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        complete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                completeMouseClicked(evt);
            }
        });
        jPanel2.add(complete, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 140, -1));

        nama.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        nama.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 210, 30));

        nombor.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        nombor.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(nombor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 130, 30));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("TOTAL PRICE :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 140, 30));

        ttprice.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 25)); // NOI18N
        ttprice.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(ttprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 110, 30));

        Datelab.setBackground(new java.awt.Color(204, 204, 204));
        Datelab.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        Datelab.setForeground(new java.awt.Color(204, 204, 204));
        Datelab.setText("dd|MM|yyyy");
        jPanel2.add(Datelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 100, 20));

        Timelab.setBackground(new java.awt.Color(204, 204, 204));
        Timelab.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        Timelab.setForeground(new java.awt.Color(204, 204, 204));
        Timelab.setText("hh:MM:ss a");
        jPanel2.add(Timelab, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 100, 20));

        jLabel11.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("DATE :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, -1, 30));

        jLabel12.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("TIME :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, -1, 30));

        time.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        time.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 140, 30));

        date.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 20)); // NOI18N
        date.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 130, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        User us = new User();
        us.setVisible(true);
        dispose();

    }//GEN-LAST:event_BackButtonMouseClicked

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void vDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vDetailsMouseClicked
        javax.swing.table.TableModel om = CustomerOrder.getModel();
        Double total = 0.0;
        int[] indexs = CustomerOrder.getSelectedRows();
        Object[] row = new Object[1];
        for (int i = 0; i < indexs.length; i++) {
            vieworder = (String) om.getValueAt(indexs[i], 0);
        }
        javax.swing.table.DefaultTableModel dt = new javax.swing.table.DefaultTableModel();
        ViewTable.setModel(dt);

        dt.addColumn("Food/Drinks Code");
        dt.addColumn("Food/Drinks Name");
        dt.addColumn("Food/Drinks Price");
        try {

            File fpath = new File("DetailsFile\\CustomerOrder");
            File f = new File(fpath, vieworder + ".txt");
            BufferedReader br;
            br = new BufferedReader(new FileReader(f));

            Object[] tableLines = br.lines().toArray();

            String line1 = tableLines[0].toString().trim();
            String[] dataRow1 = line1.split("/");
            nama.setText(" " + dataRow1[0]);
            nombor.setText(dataRow1[1]);
            date.setText(dataRow1[2]);
            time.setText(dataRow1[3]);

            for (int i = 1; i < tableLines.length; i++) {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                dt.addRow(dataRow);
            }
            for (int i = 1; i < tableLines.length; i++) {
                String line = tableLines[i].toString();
                String[] dataRow = line.split("/");
                total = total + Double.parseDouble(dataRow[2]);
            }
            totalprice = String.valueOf(total);
            ttprice.setText("RM " + totalprice);

            br.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_vDetailsMouseClicked

    private void completeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_completeMouseClicked

        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) CustomerOrder.getModel();
        int[] rows = CustomerOrder.getSelectedRows();
        for (int i = 0; i < rows.length; i++) {
            
            String u = (String) model.getValueAt(rows[i], 0);
            File f = new File("DetailsFile/CustomerOrder/" + u + ".txt");
            f.renameTo(new File("DetailsFile/CompletedOrder/" + u + ".txt"));
            
            model.removeRow(rows[i] - i);
        }
        
            javax.swing.table.DefaultTableModel dt = new javax.swing.table.DefaultTableModel();
            ViewTable.setModel(dt);

            dt.addColumn("Food/Drinks Code");
            dt.addColumn("Food/Drinks Name");
            dt.addColumn("Food/Drinks Price");
            dt.setRowCount(0);
            nama.setText("");
            nombor.setText("");
            ttprice.setText("");
       

        
    }//GEN-LAST:event_completeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackButton;
    private javax.swing.JTable CustomerOrder;
    private javax.swing.JLabel Datelab;
    private javax.swing.JLabel LogoutButton;
    private javax.swing.JLabel Timelab;
    private javax.swing.JTable ViewTable;
    private javax.swing.JLabel complete;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nombor;
    private javax.swing.JLabel smsg;
    private javax.swing.JLabel time;
    private javax.swing.JLabel ttprice;
    private javax.swing.JLabel vDetails;
    // End of variables declaration//GEN-END:variables
}
